title: ArcMeteor's Blog
email: wojiadeyuzhu@outlook.com
description: ArcMeteor's private space
timezone: Aisa/Beijing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arc-meteor.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Arc-Meteor
theme: Jekyll-theme-minima
plugins:
  - jekyll-feed
